# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AugmentedTranslationSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
   pod 'ZXingObjC', '~> 3.2.2'

  # Pods for AugmentedTranslationSample

  target 'AugmentedTranslationSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AugmentedTranslationSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
